/**
 * SFML Mining Game - Main Entry Point
 * 
 * This is a simple but educational mining game built with SFML.
 * The goal is to mine ores and trade them for pickaxe upgrades.
 * 
 * Game Features:
 * - Move around with WASD or arrow keys
 * - Mine ores by getting close to them and pressing SPACE
 * - Collect 4 types of ores: Copper, Iron, Gold, Diamond
 * - Trade ores for upgrades in the shop (press S to open/close)
 * - Upgrade your mining speed, range, and ore multiplier
 * 
 * This code is designed to be educational, with extensive comments
 * explaining how each part works and why it's structured this way.
 * 
 * @author Generated by GitHub Copilot for educational purposes
 */

#include "Game.h"
#include <iostream>

int main() {
    try {
        // Create and run the game
        // The Game class handles everything: window creation, game loop, rendering
        Game game;
        game.run();
    }
    catch (const std::exception& e) {
        // If something goes wrong, print the error message
        // This helps with debugging if the game crashes
        std::cerr << "Error: " << e.what() << std::endl;
        return -1;
    }
    
    // If we get here, the game closed normally
    return 0;
}